### ISSUE TITLE
Rename default value of HAYHOOKS_ADDITIONAL_PYTHONPATH

### ISSUE THREAD

**Issue by alex-stoica** [deepset-ai/hayhooks#28]
Currently, it is `opt/custom-components`. I recommend renaming it to `opt/custom_components` for improved consistency with Python naming conventions. This change will facilitate more intuitive imports, such as: 
`from custom_components.some_custom_component import MyCustomComponent`

**Comment by masci** [comment]
Hi @alex-stoica do you mind opening a quick PR? I'll review and merge!

**Comment by karbasia** [comment]
@masci @alex-stoica is there anything special needed to import custom components?

My `HAYHOOKS_ADDITIONAL_PYTHONPATH` is set to /opt/custom_components and I see the files on my container. When attempting to import the pipeline, I am greeted with this error message:

`Error deploying pipeline: Unable to parse Haystack Pipeline ingest_pipeline: Component 'custom_components.ocr_pdf.OCRPDFToDocument' not imported.`

My pipelines run fine locally (using the same custom_components folder in my local environment) and pipelines without custom components are also correctly imported.

I have a simple docker compose too:
```yml
services:
  hayhooks:
    container_name: hayhooks
    image: hayhooks:local
    ports:
      - 1416:1416
    volumes:
      - ./pipelines:/opt/pipelines
      - ./custom_components:/opt/custom_components
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:1416/status || exit 1"]
      interval: 120s
      timeout: 30s
      retries: 3
    env_file:
      - .env
networks:
  default:
    name: local
```
